export enum AccessoryCategory {
    Other = 1,
    Bridge = 2,
    Fan = 3,
    Garage = 4,
    Lightbulb = 5,
    DoorLock = 6,
    Outlet = 7,
    Switch = 8,
    Thermostat = 9,
    Sensor = 10,
    SecuritySystem = 11,
    Door = 12,
    Window = 13,
    WindowCovering = 14,
    ProgrammableSwitch = 15,
    RangeExtender = 16,
    IPCamera = 17,
    VideoDoorBell = 18,
    AirPurifier = 19
}